export enum QUEUES {
  ADD_AUTH_TO_DB = 'addAuthToDB',
  ADD_COMMENT_TO_DB = 'addCommentToDB',
  SEND_FORGOT_PASSWORD_EMAIL = 'sendForgotPasswordEmail',
  SEND_RESET_PASSWORD_EMAIL = 'sendResetPasswordEmail',
  ADD_FOLLOWER_TO_DB = 'addFollowerToDB',
  REMOVE_FOLLOWER_FROM_DB = 'removeFollowerFromDB',
  ADD_POST_TO_DB = 'addPostToDB',
  DELETE_POST_FROM_DB = 'deletePostFromDB',
  UPDATE_POST_IN_DB = 'updatePostInDB',
  ADD_USER_TO_DB = 'addUserToDB',
  UPDATE_BLOCKED_USER_IN_DB = 'updateBlockedUserToDB',
  ADD_REACTION_TO_DB = 'addReactionToDB',
  REMOVE_REACTION_FROM_DB = 'removeReactionFromDB',
  ADD_CHAT_TO_DB = 'addChatToDB',
  MARK_MESSAGES_AS_READ_IN_DB = 'markMessagesAsReadInDB',
  SEND_NOTIFICATION_COMMENT = 'sendNotificationComment',
  SEND_NOTIFICATION_FOLLOWER = 'sendNotificationFollower',
  SEND_NOTIFICATION_REACTION = 'sendNotificationReaction',
  NOTIFY_COMMENT_EMAIL = 'notifyCommentEmail',
  NOTIFY_FOLLOWER_EMAIL = 'notifyFollowerEmail',
  NOTIFY_REACTION_EMAIL = 'notifyReactionEmail'
}
