export enum QUEUES {
  ADD_AUTH_TO_DB = 'addAuthToDb',
  ADD_COMMENT_TO_DB = 'addCommentToDb',
  SEND_FORGOT_PASSWORD_EMAIL = 'sendForgotPasswordEmail',
  SEND_RESET_PASSWORD_EMAIL = 'sendResetPasswordEmail',
  ADD_FOLLOWER_TO_DB = 'addFollowerToDb',
  REMOVE_FOLLOWER_FROM_DB = 'removeFollowerFromDb',
  ADD_POST_TO_DB = 'addPostToDb',
  DELETE_POST_FROM_DB = 'deletePostFromDb',
  UPDATE_POST_IN_DB = 'updatePostInDb',
  ADD_USER_TO_DB = 'addUserToDb',
  UPDATE_BLOCKED_USER_IN_DB = 'updateBlockedUserToDb',
  ADD_REACTION_TO_DB = 'addReactionToDb',
  REMOVE_REACTION_FROM_DB = 'removeReactionFromDb',
  SEND_NOTIFICATION_COMMENT = 'sendNotificationComment',
  SEND_NOTIFICATION_FOLLOWER = 'sendNotificationFollower',
  SEND_NOTIFICATION_REACTION = 'sendNotificationReaction',
  NOTIFY_COMMENT_EMAIL = 'notifyCommentEmail',
  NOTIFY_FOLLOWER_EMAIL = 'notifyFollowerEmail',
  NOTIFY_REACTION_EMAIL = 'notifyReactionEmail'
}
