@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/comment/6667363d274f7b4549064e71
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "comment": "my comment 1`"
}

###
GET {{baseUrl}}/{{urlPath}}/comments/6659ee3f25e0ae569691a8f1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/comments-names/6659ee3f25e0ae569691a8f1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/comment/6659ee3f25e0ae569691a8f1/665c0727f6cc69d57cbc1db9
Content-Type: application/json
Accept: application/json
withCredentials: true
