@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/follow/66673c5cd3406a52a982cfc2
Content-Type: application/json
Accept: application/json
withCredentials: true


###
PUT {{baseUrl}}/{{urlPath}}/unfollow/6633870d41901aeb6e55d66f
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/followings
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/followers/6633870d41901aeb6e55d66f
Content-Type: application/json
Accept: application/json
withCredentials: true
