@baseUrl = http://localhost:5000
@urlPath = api/v1

POST {{baseUrl}}/{{urlPath}}/post/reactions/
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "Chau",
  "postId": "6659ee3f25e0ae569691a8f1",
  "type": "like",
  "profilePicture": "https://res.cloudinary.com/dlbhnqmyr/image/upload/v1711805433/660813f89f80db7b57daf3c9",
  "previousReaction": ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/6659ee3f25e0ae569691a8f1/like
Content-Type: application/json
Accept: application/json
withCredentials: true

###

GET {{baseUrl}}/{{urlPath}}/post/reactions/6659ee3f25e0ae569691a8f1/
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/reaction/6659ee3f25e0ae569691a8f1/chau
Content-Type: application/json
Accept: application/json
withCredentials: true
